# Generated by Django 5.0.3 on 2024-04-11 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_professor_sts_alter_student_pros"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="pros",
        ),
        migrations.RemoveField(
            model_name="studentprofessor",
            name="professors",
        ),
        migrations.RemoveField(
            model_name="student",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="student",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="studentprofessor",
            name="students",
        ),
        migrations.CreateModel(
            name="ProfessorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        default="", max_length=25, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        default="", max_length=50, verbose_name="Last Name"
                    ),
                ),
                (
                    "national_no",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="National Number"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentprofessor",
            name="professor",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.professorprofile",
            ),
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        default="", max_length=25, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        default="", max_length=50, verbose_name="Last Name"
                    ),
                ),
                (
                    "stu_no",
                    models.CharField(max_length=10, verbose_name="Student Number"),
                ),
                ("is_ta", models.BooleanField(default=False)),
                ("phone_no", models.IntegerField(verbose_name="Phone Number")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="students",
            field=models.ManyToManyField(
                default=None,
                related_name="professors",
                through="users.StudentProfessor",
                to="users.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="studentprofessor",
            name="student",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.studentprofile",
            ),
        ),
        migrations.DeleteModel(
            name="Professor",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
