# Generated by Django 5.0.3 on 2024-04-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="phone_no",
            field=models.CharField(verbose_name="Phone Number"),
        ),
    ]
