# Generated by Django 5.0.3 on 2024-04-11 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_student_pros_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professorprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="professorprofile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="last_name",
        ),
    ]
