# Generated by Django 5.0.4 on 2024-04-17 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_professorprofile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('term', models.IntegerField(verbose_name='Term')),
                ('required_TAs', models.IntegerField(verbose_name='Required TAs')),
                ('num_applicants', models.IntegerField(default=0, verbose_name='Number of Applicants')),
                ('num_tas', models.IntegerField(default=0, verbose_name='Number of TAs')),
                ('section', models.IntegerField(verbose_name='Section')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.professorprofile')),
            ],
        ),
    ]
