# Generated by Django 5.0.3 on 2024-05-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_studentprofile_phone_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Course Name"
            ),
        ),
    ]
