# Generated by Django 5.0.6 on 2024-05-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_course_description_alter_course_minpoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professorprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="average",
            field=models.IntegerField(default=0, verbose_name="Rating Count"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="rate_count",
            field=models.IntegerField(default=0, verbose_name="Rating Count"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="rate_sum",
            field=models.IntegerField(default=0, verbose_name="Rating Sum"),
        ),
    ]
