# Generated by Django 5.0.6 on 2024-05-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_professorprofile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professorprofile",
            name="about_me",
            field=models.TextField(default="", verbose_name="About Me"),
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="college",
            field=models.CharField(default="", max_length=20, verbose_name="College"),
        ),
        migrations.AddField(
            model_name="professorprofile",
            name="university",
            field=models.CharField(
                default="", max_length=20, verbose_name="University"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="about_me",
            field=models.TextField(default="", verbose_name="About Me"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="college",
            field=models.CharField(default="", max_length=20, verbose_name="College"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="enter_year",
            field=models.IntegerField(default=0, verbose_name="Enter Year"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="gpa",
            field=models.FloatField(default=0, verbose_name="GPA"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="major",
            field=models.CharField(default="", verbose_name="Major"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="university",
            field=models.CharField(
                default="", max_length=20, verbose_name="University"
            ),
        ),
    ]
