# Generated by Django 5.0.6 on 2024-06-06 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_professorprofile_about_me_professorprofile_college_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessorFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="professor_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "professor_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="users.professorprofile",
                    ),
                ),
                (
                    "uploaded_by_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.studentprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("uploaded_by_student", "professor_profile")},
            },
        ),
    ]
