# Generated by Django 5.0.6 on 2024-06-07 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_professorfiles"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="professorfiles",
            unique_together=set(),
        ),
    ]
